### ISSUE TITLE
TypeError on passing passing `onchange` to `hb.shape`

### ISSUE THREAD

**Issue by ArchitBhonsle** [simoncozens/vharfbuzz#11]
Here's my code:
```py
from vharfbuzz import Vharfbuzz

poppins = Vharfbuzz("Fonts/Poppins//Poppins-Regular.ttf")

def myOnchange(self, stage, lookupid, buf):
    print(self, stage, lookupid, buf)

buf = poppins.shape("Archit", onchange=myOnchange)
print(poppins.buf_to_svg(buf))
```

This gives me the following error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: Vharfbuzz.make_message_handling_function.<locals>.handle_message() missing 1 required positional argument: 'buf2'
Exception ignored in: 'uharfbuzz._harfbuzz.msgcallback'
Traceback (most recent call last):
  File "C:\Users\abhon\AppData\Roaming\Python\Python310\site-packages\vharfbuzz\__init__.py", line 113, in shape
    hb.shape(self.hbfont, buf, features, shapers=shapers)
TypeError: Vharfbuzz.make_message_handling_function.<locals>.handle_message() missing 1 required positional argument: 'buf2'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: Vharfbuzz.make_message_handling_function.<locals>.handle_message() missing 1 required positional argument: 'buf2'
Exception ignored in: 'uharfbuzz._harfbuzz.msgcallback'
Traceback (most recent call last):
  File "C:\Users\abhon\AppData\Roaming\Python\Python310\site-packages\vharfbuzz\__init__.py", line 113, in shape
    hb.shape(self.hbfont, buf, features, shapers=shapers)
TypeError: Vharfbuzz.make_message_handling_function.<locals>.handle_message() missing 1 required positional argument: 'buf2'
```

The error comes from [here](https://github.com/simoncozens/vharfbuzz/blob/main/lib/vharfbuzz/__init__.py#L113) but I don't see what I'm doing wrong. Passing the `onchange` is what triggers this error.

**Comment by ArchitBhonsle** [comment]
I think I understand what is going on here. The below function calls the `handle_message` function with only one argument `msg`.
https://github.com/harfbuzz/uharfbuzz/blob/f8b12cb12f9cdd79be281f3f218293b8ba59a4b2/src/uharfbuzz/_harfbuzz.pyx#L30-L34

While `make_message_handling_function` creates a callback that takes in two parameters.
https://github.com/simoncozens/vharfbuzz/blob/fdc52bc3c42ff18f58c4522f8742a955051a045c/lib/vharfbuzz/__init__.py#L45-L64

More importantly, `Vharfbuzz.history` is empty after a call to `Vharfbuzz.shape`.

```py
def myOnchange(self, stage, lookupid, buf):
    print("hello")
    print(self, stage, lookupid, buf)

buf = poppins.shape("देवनागरी", onchange=myOnchange)
print(poppins.history)  // Outputs: {'GSUB': [], 'GPOS': []}
```

I think this is probably due to some change to harfbuzz interally. I'll use `uharfbuzz` for now. I'm quite to new to harfbuzz in general but if I understand the problem I'll create a pull request in the future.
